### PR TITLE
USWDS styling addition

### LINKED ISSUE #144: Adjust OPAT searchable index CSS to match USWDS theme
We can use the CSS from the USWDS Federalist Jekyll theme and make the changes.

### PR DESCRIPTION
**Pull request by dmundra**
Closes #144 

This adds all the USWDS files (in multiple locations) because that is how our examples are set up. The diff is quite large so I would just focus on downloading the files and seeing if that renders the styling correctly or not.

Link: https://github.com/GSA/open-product-accessibility-template/pull/146/checks?check_run_id=3416397888

Also, review the website pull request to see it live: https://github.com/GSA/opat-website/pull/12

### CODE REVIEW

**Comment by dmundra** [comment]
Unfortunately, there is no official CDN so I have to commit all the files. See https://github.com/uswds/uswds/pull/1100#issuecomment-207456638 for background.

**Comment by mgifford** [comment]
> Unfortunately, there is no official CDN so I have to commit all the files. See [uswds/uswds#1100 (comment)](https://github.com/uswds/uswds/pull/1100#issuecomment-207456638) for background.

So wait. Are you telling me that because USDS doesn't have a CDN we could just use as a reference, I have to review 4,789 changed files rather than maybe 10?

Screen Shot of 4,789 changed files in GitHub

If we want to incorporate the USWDS theme suddenly we have to take on the maintenance of thousands of build files (rather than just add some links to USDS hosted CSS & JS files?)?

**Review by mgifford — APPROVED** [review]
Works fine for me. Thanks!



Screen Shot 2021-08-25 at 9 17 22 AM

**Comment by dmundra** [comment]
Yup no CDN. We wouldn't be maintaining the files per se just adding them to the repo. The output process will copy the files from the npm package whenever it is run. This is useful so that you get the necessary styling together with the HTML files.

**Pull request merged**
