### PR TITLE
Cleaning up images, adding new ones & adding text

### PR DESCRIPTION
**Pull request by mgifford**
Cleaning up images and adding text.

### CODE REVIEW

**Comment by dmundra** [comment]
@mgifford looks like the images in options https://github.com/GSA/open-product-accessibility-template/blob/mgifford-patch-1/docs/ROADMAP.md are slightly bigger than the base period.

**Comment by mgifford** [comment]
> @mgifford looks like the images in options https://github.com/GSA/open-product-accessibility-template/blob/mgifford-patch-1/docs/ROADMAP.md are slightly bigger than the base period.

I think this is because the text box is a different size. If we add more text then they should line up. I don't think that the images have any different size specifications that would cause this. I could be wrong about that, but think it may not be something we have much control over.

**Comment by dmundra** [comment]
Ah got it. Thanks for the clarification. I think one idea would be to force the width on the table cell but that is overkill.

**Review by dmundra — APPROVED** [review]
Looking good.

**Pull request merged**
